login: &login
  adapter: mysql2
  host: localhost
  username: gadgets
  password: gadgets

development: &development
  database: gadgets_dev
  <<: *login

test: &test
  database: gadgets_test
  <<: *login

production: &production
  database: gadgets
  <<: *login
